#!/bin/bash

set -e

rm -rf out
./tools/gn/bootstrap/bootstrap.py
out/gn_unittests

# Check in-tree vs. ours. Uses:
# - Chromium tree at 556eead9ce1e in /work/cr/src.
# - out/lin/gn as built in-tree binary

pushd /work/cr/src
rm -rf out/COMP
out/lin/gn gen out/COMP
mv out/COMP out/a
rm -rf out/COMP
/work/gn/out/gn gen out/COMP
mv out/COMP out/b
# only diff should be regen line
diff -r out/a out/b
popd
